/*
 * Copyright 2015 Vikour.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gui.juegos.traducir_palabras;

import gui.componentes.JRoutedPanel;
import gui.util.GestionPaneles;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import lanword.controladores.juegos.JuegosCtrl;
import lanword.controladores.juegos.PartidaJuegoTraducir;
import lanword.interfaces.bd.BDManagment;
import lanword.interfaces.bd.BDResolver;
import lanword.modelo.Grupo;
import lanword.modelo.Idioma;
import lanword.modelo.Palabra;

/**
 *
 * @author vikour
 */
public class JPanelInicio extends JRoutedPanel {

    public JPanelInicio(GestionPaneles gesPanel) {
        super(gesPanel);
        initComponents();
        customInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButtonAdministracion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxIdiomaGrupo = new javax.swing.JComboBox();
        jComboBoxIdioma = new javax.swing.JComboBox();
        JLabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButtonAdministracion.setText("Ir a adminsitración");
        jButtonAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministracionActionPerformed(evt);
            }
        });

        jButton2.setText("Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("El juego consiste en traducir palabras de un idioma o grupo a ");

        jLabel3.setText("Idioma o grupo:");

        jLabel4.setText("Idioma de traducción: ");

        JLabelError.setForeground(new java.awt.Color(220, 31, 31));

        jLabel1.setText("otro idioma. Más  abajo  podrás  elegir  los  parámetros  para");

        jLabel5.setText("empezar la partida.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLabelError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdministracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBoxIdiomaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxIdioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIdiomaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JLabelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministracionActionPerformed
        gui.WindowsController.getInstance().showAdministracion();
        Window dialog = SwingUtilities.getWindowAncestor(this);
        dialog.setVisible(false);
    }//GEN-LAST:event_jButtonAdministracionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Object idiomaGrupoSelected = jComboBoxIdiomaGrupo.getSelectedItem();
        Object idiomaSelected = jComboBoxIdioma.getSelectedItem();
        PartidaJuegoTraducir partida;
        ArrayList<Palabra> palabras;
        BDManagment bd = null;

        if (idiomaGrupoSelected.equals(idiomaSelected))
            JLabelError.setText("Los idiomas no pueden ser los mismos.");
        else try {
            bd = BDResolver.getInstance();
            
            if (idiomaGrupoSelected instanceof Idioma)
                palabras = bd.palabras.buscarAleatoriamente((Idioma) idiomaGrupoSelected, (Idioma) idiomaSelected);
            else
                palabras = bd.palabras.buscarAleatoriamente((Grupo) idiomaGrupoSelected, (Idioma) idiomaSelected);
            
            if (palabras.size() < 10) 
                JLabelError.setText("Debe tener al menos 10 palabras traducibles.");
            else {
                partida = new PartidaJuegoTraducir(palabras, (Idioma) idiomaSelected);
                JuegosCtrl.getInstance().setPartida(partida);
                getGestorPaneles().setVisiblePanel(new JPanelTraducir(getGestorPaneles()), false);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JPanelInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JPanelInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JPanelInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelError;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdministracion;
    private javax.swing.JComboBox jComboBoxIdioma;
    private javax.swing.JComboBox jComboBoxIdiomaGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

    private void customInitComponents() {
        try {
            BDManagment bd = BDResolver.getInstance();
            Object idiomas[] = null;
            Object grupos[] = null;
            Object idiomasGrupos[] = null;
            ActionListener ALFlush = new OnActionFlushError();
            
            // Se llena el combo box con idiomas y grupos.
            idiomas = bd.idiomas.buscar().toArray();
            grupos = bd.grupos.buscar().toArray();
            
            // Se genera una array conjunta entre los dos resultados.
            idiomasGrupos = new Object[idiomas.length + grupos.length];
            
            for (int i = 0 ; i < idiomas.length ; i++)
                idiomasGrupos[i] = idiomas[i];
            
            for (int i = 0 ; i < grupos.length ; i++)
                idiomasGrupos[i + idiomas.length] = grupos[i];
            
            // Se establecen los resultados los combo box.
            jComboBoxIdiomaGrupo.setModel(new DefaultComboBoxModel(idiomasGrupos));
            jComboBoxIdioma.setModel(new DefaultComboBoxModel(idiomas));

            // Se añade un listener para borrar los errores mostrados, cuando hay alguna acción.
            jComboBoxIdioma.addActionListener(ALFlush);
            jComboBoxIdiomaGrupo.addActionListener(ALFlush);

        } catch (SQLException ex) {
            Logger.getLogger(JPanelInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JPanelInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JPanelInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private class OnActionFlushError implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JLabelError.setText("");
        }
        
    }
}
